# Section 6: final 
# Part of the CLAID notebook (see CLAID_notebook.py for the full script).
"""CLAID notebook converted to a plain Python script.

Generated by tools/convert_notebook.py - run it from the repository root:

    python notebook_to_py/CLAID_notebook.py

The runtime fixes it applies are listed in notebook_to_py/conversion_report.txt.
Figures are written to notebook_to_py/output/ instead of opening a window.
"""
import os
import sys

import matplotlib

matplotlib.use("Agg")  # headless: every plt.show() is captured by claid_show()
import matplotlib.pyplot as plt  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUTPUT_DIR = os.path.join(HERE, "output")
DATASET_PATH = os.path.join(ROOT, "data", "Dataset.csv")  # extracted from the dataset zip
RUN_SCRAPER = False  # the example.com word-graph demo needs internet access

os.makedirs(OUTPUT_DIR, exist_ok=True)
_FIG_N = [0]


def claid_show():
    """Save the current figure (the notebook called plt.show() here)."""
    _FIG_N[0] += 1
    fig = plt.gcf()
    if fig.get_axes():
        path = os.path.join(OUTPUT_DIR, "fig_%02d.png" % _FIG_N[0])
        fig.savefig(path, dpi=110, bbox_inches="tight")
        print("  [saved] %s" % os.path.relpath(path, ROOT))
    plt.close("all")


sys.path.insert(0, os.path.join(ROOT, "src"))

import community as community_louvain  # noqa: E402,F401  (python-louvain)
import networkx as nx  # noqa: E402,F401
import pandas as pd  # noqa: E402,F401
from networkx.algorithms import community  # noqa: E402,F401

assert os.path.exists(DATASET_PATH), "dataset not found: %s" % DATASET_PATH

# CLAID notebook - final  (30 cells)


# % [cell 24] code
# pip install igraph   (run once: python -m pip install igraph)
try:
    import igraph as ig  # noqa: F401  (optional: python -m pip install igraph)
except ImportError:  # pragma: no cover - optional dependency
    ig = None
import pandas as pd
import networkx as nx
from networkx.algorithms import community
import community as community_louvain
import matplotlib.pyplot as plt
try:
    import igraph as ig  # noqa: F401  (optional: python -m pip install igraph)
except ImportError:  # pragma: no cover - optional dependency
    ig = None
# %matplotlib inline  -> handled by the 'Agg' backend in the preamble
G = nx.karate_club_graph()
# Define the graph G
G = nx.karate_club_graph()

# Draw the graph
nx.draw_networkx(G)
lst_b = nx.algorithms.community.girvan_newman(G)
type(lst_b)
for x in lst_b:
  print(x)
colors = ["#00C98D", "#5030C0", "#50F0F0"]
pos = nx.spring_layout(G)
lst_b = community.girvan_newman(G)
color_map_b = {}
keys = G.nodes()
values = "black"
for i in keys:
        color_map_b[i] = values
counter = 0
for x in lst_b:
  print(1)
  for c in x:
    for n in c:
      color_map_b[n] = colors[counter % len(colors)]
    counter = counter + 1
  break
nx.draw_networkx_edges(G, pos)
nx.draw_networkx_nodes(G, pos, node_color=dict(color_map_b).values())
nx.draw_networkx_labels(G, pos)
plt.axis("off")
claid_show()
modularity = []
for x in lst_b:
  modularity.append(community.modularity(G, x))
modularity
plt.plot(modularity, 'o')
plt.xlabel('# of clusters')
plt.ylabel('modularity')
claid_show()
max_modularity = max(modularity)
max_community = None

for comm_set, mod_value in zip(lst_b, modularity):
    if mod_value == max_modularity:
        max_community = comm_set
        break  # Stop after finding the maximum modularity community

if max_community:
    # Community visualization for the max_community
    colors = ["#00C98D", "#5030C0", "#50F0F0", 'red', 'blue']
    pos = nx.spring_layout(G)
    color_map_b = {}
    keys = G.nodes()
    values = "black"
    for i in keys:
        color_map_b[i] = values
    counter = 0
    for x in max_community:
        for n in x:
            color_map_b[n] = colors[counter % len(colors)]
        counter = counter + 1

    nx.draw_networkx_edges(G, pos)
    nx.draw_networkx_nodes(G, pos, node_color=dict(color_map_b).values())
    nx.draw_networkx_labels(G, pos)
    plt.axis("off")
    claid_show()
else:
    print("No community found with maximum modularity.")
community.greedy_modularity_communities(G)
#Community visualization
colors = ["#00C98D", "#5030C0", "#50F0F0"]
pos = nx.spring_layout(G)
lst_b = community.greedy_modularity_communities(G)
color_map_b = {}
keys = G.nodes()
values = "black"
for i in keys:
        color_map_b[i] = values
counter = 0
for x in lst_b:
  for n in x:
    color_map_b[n] = colors[counter % len(colors)]
  counter = counter + 1

nx.draw_networkx_edges(G, pos)
nx.draw_networkx_nodes(G, pos, node_color=dict(color_map_b).values())
nx.draw_networkx_labels(G, pos)
plt.axis("off")
claid_show()
colors = ["#00C98D", "#5030C0", "#50F0F0"]
pos = nx.spring_layout(G)
lst_m = community.label_propagation_communities(G)
color_map_b = {}
keys = G.nodes()
values = "black"
for i in keys:
        color_map_b[i] = values
counter = 0
for c in lst_m:
  for n in c:
    color_map_b[n] = colors[counter % len(colors)]
  counter = counter + 1
nx.draw_networkx_edges(G, pos)
nx.draw_networkx_nodes(G, pos, node_color=dict(color_map_b).values())
nx.draw_networkx_labels(G, pos)
plt.axis("off")
claid_show()
# pip install community   (run once: python -m pip install community)
import networkx as nx
from community import community_louvain
import matplotlib.pyplot as plt

# Assuming G is defined and has nodes and edges added to it
G = nx.Graph()

# Generate a sample graph for demonstration
G.add_edges_from([(1, 2), (2, 3), (3, 4), (4, 1)])

colors = ["#00C98D", "#5030C0", "#50F0F0", 'yellow']
pos = nx.spring_layout(G)
lst_m = community_louvain.best_partition(G)
color_map_b = {}
keys = G.nodes()
values = "black"
for i in keys:
        color_map_b[i] = values

for n in dict(lst_m):
  color_map_b[n] = colors[lst_m[n]]

plt.figure(figsize=(8, 8))  # Increase the figure size
nx.draw_networkx_edges(G, pos)
nx.draw_networkx_nodes(G, pos, node_color=dict(color_map_b).values())
nx.draw_networkx_labels(G, pos)
plt.axis("off")
claid_show()

import requests
from bs4 import BeautifulSoup
import networkx as nx
import matplotlib.pyplot as plt

# Function to scrape data from a website
def scrape_website(url):
    try:
        response = requests.get(url)
        if response.status_code == 200:
            soup = BeautifulSoup(response.text, 'html.parser')
            # Extract relevant data from the website
            # Example: titles, links, text, etc.
            # For simplicity, let's extract text content
            text_content = soup.get_text()
            return text_content
        else:
            print("Failed to retrieve data from:", url)
            return None
    except Exception as e:
        print("Error occurred:", e)
        return None

# Main function for network analysis
def main():
    # Define the URL to scrape
    url = "https://example.com"

    # Scrape data from the website
    text_content = scrape_website(url)

    # If data is successfully scraped, perform network analysis
    if text_content:
        # Create a graph
        G = nx.Graph()

        # Process text content (you may need more advanced text processing here)
        # For simplicity, let's split text by whitespace
        words = text_content.split()

        # Add nodes and edges to the graph
        for i in range(len(words) - 1):
            word1 = words[i]
            word2 = words[i + 1]
            if not G.has_edge(word1, word2):
                G.add_edge(word1, word2)

        # Visualize the network
        pos = nx.spring_layout(G)
        plt.figure(figsize=(10, 10))
        nx.draw(G, pos, with_labels=True, node_color='skyblue', node_size=1000, edge_color='black', linewidths=1, font_size=15)
        plt.title("Website Network Analysis")
        claid_show()
    else:
        print("Failed to scrape data. Exiting...")

if __name__ == "__main__" and RUN_SCRAPER:
    main()


# % [cell 25] code


# % [cell 26] code
import networkx as nx
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score
from networkx.algorithms import community

# Assuming G is defined and has nodes and edges added to it
G = nx.Graph()

# Generate a sample graph for demonstration
G.add_edges_from([(1, 2), (2, 3), (3, 4), (4, 1)])

colors = ["#00C98D", "#5030C0", "#50F0F0", 'yellow']
pos = nx.spring_layout(G)
lst_m = community.greedy_modularity_communities(G)
color_map_b = {}
keys = G.nodes()
values = "black"
for i in keys:
        color_map_b[i] = values

# Assuming ground truth labels are available
ground_truth_labels = {1: 0, 2: 0, 3: 1, 4: 1}  # Example ground truth labels

predicted_labels = []
for node in G.nodes():
    for i, community in enumerate(lst_m):
        if node in community:
            predicted_labels.append(i)
            break

# Calculate F1 score
f1 = f1_score(list(ground_truth_labels.values()), predicted_labels, average='weighted')

print("F1 Score:", f1)

# Calculate betweenness centrality for each node within each community
betweenness_centralities = {}
for i, community in enumerate(lst_m):
    community_subgraph = G.subgraph(community)
    betweenness_centralities[i] = nx.betweenness_centrality(community_subgraph)

# Visualize the betweenness centrality for nodes within each community
for i, community in enumerate(lst_m):
    community_subgraph = G.subgraph(community)
    node_colors = [betweenness_centralities[i][node] for node in community_subgraph.nodes()]
    nx.draw_networkx_edges(G, pos)
    # Use plt.scatter() to create nodes and get a mappable object
    nodes = nx.draw_networkx_nodes(G, pos, node_color=node_colors, cmap=plt.cm.Blues)
    nx.draw_networkx_labels(G, pos)
    plt.title(f"Community {i} Betweenness Centrality")
    # Create colorbar using the mappable object returned by plt.scatter()
    plt.colorbar(nodes, label='Betweenness Centrality')
    plt.axis("off")
    claid_show()
