# Section 7: Calculate centrality measures
# Part of the CLAID notebook (see CLAID_notebook.py for the full script).
"""CLAID notebook converted to a plain Python script.

Generated by tools/convert_notebook.py - run it from the repository root:

    python notebook_to_py/CLAID_notebook.py

The runtime fixes it applies are listed in notebook_to_py/conversion_report.txt.
Figures are written to notebook_to_py/output/ instead of opening a window.
"""
import os
import sys

import matplotlib

matplotlib.use("Agg")  # headless: every plt.show() is captured by claid_show()
import matplotlib.pyplot as plt  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUTPUT_DIR = os.path.join(HERE, "output")
DATASET_PATH = os.path.join(ROOT, "data", "Dataset.csv")  # extracted from the dataset zip
RUN_SCRAPER = False  # the example.com word-graph demo needs internet access

os.makedirs(OUTPUT_DIR, exist_ok=True)
_FIG_N = [0]


def claid_show():
    """Save the current figure (the notebook called plt.show() here)."""
    _FIG_N[0] += 1
    fig = plt.gcf()
    if fig.get_axes():
        path = os.path.join(OUTPUT_DIR, "fig_%02d.png" % _FIG_N[0])
        fig.savefig(path, dpi=110, bbox_inches="tight")
        print("  [saved] %s" % os.path.relpath(path, ROOT))
    plt.close("all")


sys.path.insert(0, os.path.join(ROOT, "src"))

import community as community_louvain  # noqa: E402,F401  (python-louvain)
import networkx as nx  # noqa: E402,F401
import pandas as pd  # noqa: E402,F401
from networkx.algorithms import community  # noqa: E402,F401

assert os.path.exists(DATASET_PATH), "dataset not found: %s" % DATASET_PATH

# CLAID notebook - Calculate centrality measures (30 cells)


# % [cell 28] code
import pandas as pd
import networkx as nx
import community as community_louvain
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score
# %matplotlib inline  -> handled by the 'Agg' backend in the preamble

# Read the dataset from the provided path
dataset_path = str(DATASET_PATH)
df = pd.read_csv(dataset_path)

# Assuming the dataset contains columns 'source_node' and 'target_node' representing edges
# If your dataset has different column names, please replace them accordingly
G = nx.from_pandas_edgelist(df, 'source_node', 'target_node')

# Anomaly Detection using Degree Centrality
degree_centrality = nx.degree_centrality(G)

# Compute mean and standard deviation of degree centrality
mean_degree_centrality = sum(degree_centrality.values()) / len(degree_centrality)
std_degree_centrality = sum([(x - mean_degree_centrality) ** 2 for x in degree_centrality.values()]) / len(degree_centrality)
threshold = mean_degree_centrality + 2 * std_degree_centrality

# Identify anomalies
anomalies = {node: centrality for node, centrality in degree_centrality.items() if centrality > threshold}

# Draw the graph with adjusted parameters
plt.figure(figsize=(12, 12))
pos = nx.spring_layout(G, k=0.15)  # Adjust 'k' to increase spacing between clusters

# Draw edges with reduced width and gray color
nx.draw_networkx_edges(G, pos, edge_color='gray', width=0.5)

# Draw normal nodes with reduced size and light blue color
nx.draw_networkx_nodes(G, pos, nodelist=[node for node in G.nodes() if node not in anomalies],
                       node_color='lightblue', node_size=100, alpha=0.8)

# Highlight anomalies in red
nx.draw_networkx_nodes(G, pos, nodelist=anomalies.keys(), node_color='red', node_size=300)

# Hide node labels
nx.draw_networkx_labels(G, pos, labels={}, font_size=12)

plt.title("Network Graph with Anomalies")
claid_show()

# Convert anomalies to a DataFrame for easier analysis
anomalies_df = pd.DataFrame.from_dict(anomalies, orient='index', columns=['Degree Centrality'])

# Calculate F1 score (assuming you have ground truth for anomalies)
# ground_truth_anomalies should be a dictionary with node IDs as keys and anomaly labels as values
# For example: ground_truth_anomalies = {'node1': 1, 'node2': 0, ...}
# Adjust the threshold as needed based on your data and requirements
ground_truth_anomalies = {}  # Replace with actual ground truth if available
predicted_anomalies = {node: 1 if centrality > threshold else 0 for node, centrality in degree_centrality.items()}
y_true = [ground_truth_anomalies.get(node, 0) for node in G.nodes()]
y_pred = [predicted_anomalies.get(node, 0) for node in G.nodes()]
f1score = f1_score(y_true, y_pred)

print("F1 Score:", f1score)
print("Anomalies:")
print(anomalies_df)


# % [cell 29] code
import pandas as pd
import networkx as nx
from sklearn.metrics import precision_score, recall_score, f1_score
from networkx.algorithms import community as nx_comm

# Read the dataset
dataset = {
    'SOURCE_SUBREDDIT': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'],
    'TARGET_SUBREDDIT': ['B', 'C', 'D', 'A', 'F', 'G', 'H', 'E'],
    'Ground_Truth_Community': [0, 0, 1, 1, 2, 2, 3, 3]  # Example ground truth labels
}

# Convert dataset to DataFrame
df = pd.DataFrame(dataset)

# Create Graph
G = nx.from_pandas_edgelist(df, 'SOURCE_SUBREDDIT', 'TARGET_SUBREDDIT')

# Ground truth labels
ground_truth_labels = dict(zip(df['SOURCE_SUBREDDIT'], df['Ground_Truth_Community']))

# Community detection
lst_m = list(nx_comm.greedy_modularity_communities(G))

# Louvain modularity
partition = nx_comm.greedy_modularity_communities(G)

# Betweenness centrality
betweenness_centralities = nx.betweenness_centrality(G)

# Convert Louvain partition to node-community mapping
louvain_labels = {}
for i, comm in enumerate(partition):
    for node in comm:
        louvain_labels[node] = i

# Calculate precision, recall, and F1 score for each method
precision_community = precision_score(list(ground_truth_labels.values()), [ground_truth_labels[node] for node in G.nodes()], average='weighted')
recall_community = recall_score(list(ground_truth_labels.values()), [ground_truth_labels[node] for node in G.nodes()], average='weighted')
f1_community = f1_score(list(ground_truth_labels.values()), [ground_truth_labels[node] for node in G.nodes()], average='weighted')

precision_louvain = precision_score(list(ground_truth_labels.values()), [louvain_labels[node] for node in G.nodes()], average='weighted')
recall_louvain = recall_score(list(ground_truth_labels.values()), [louvain_labels[node] for node in G.nodes()], average='weighted')
f1_louvain = f1_score(list(ground_truth_labels.values()), [louvain_labels[node] for node in G.nodes()], average='weighted')

# Convert betweenness centrality scores to subreddit labels
betweenness_labels = {subreddit: max(betweenness_centralities, key=betweenness_centralities.get) for subreddit in ground_truth_labels.keys()}

# Calculate precision, recall, and F1 score for betweenness centrality
precision_betweenness = precision_score(list(ground_truth_labels.values()), [ground_truth_labels[node] for node in betweenness_labels.keys()], average='weighted')
recall_betweenness = recall_score(list(ground_truth_labels.values()), [ground_truth_labels[node] for node in betweenness_labels.keys()], average='weighted')
f1_betweenness = f1_score(list(ground_truth_labels.values()), [ground_truth_labels[node] for node in betweenness_labels.keys()], average='weighted')

# Tabulate the results
results = pd.DataFrame({
    'Method': ['Community Detection', 'Louvain Modularity', 'Betweenness Centrality'],
    'Precision': [precision_community, precision_louvain, precision_betweenness],
    'Recall': [recall_community, recall_louvain, recall_betweenness],
    'F1 Score': [f1_community, f1_louvain, f1_betweenness]
})

print(results)
