# Section 2: Edge betweenness (Girvan–Newman)
# Part of the CLAID notebook (see CLAID_notebook.py for the full script).
"""CLAID notebook converted to a plain Python script.

Generated by tools/convert_notebook.py - run it from the repository root:

    python notebook_to_py/CLAID_notebook.py

The runtime fixes it applies are listed in notebook_to_py/conversion_report.txt.
Figures are written to notebook_to_py/output/ instead of opening a window.
"""
import os
import sys

import matplotlib

matplotlib.use("Agg")  # headless: every plt.show() is captured by claid_show()
import matplotlib.pyplot as plt  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUTPUT_DIR = os.path.join(HERE, "output")
DATASET_PATH = os.path.join(ROOT, "data", "Dataset.csv")  # extracted from the dataset zip
RUN_SCRAPER = False  # the example.com word-graph demo needs internet access

os.makedirs(OUTPUT_DIR, exist_ok=True)
_FIG_N = [0]


def claid_show():
    """Save the current figure (the notebook called plt.show() here)."""
    _FIG_N[0] += 1
    fig = plt.gcf()
    if fig.get_axes():
        path = os.path.join(OUTPUT_DIR, "fig_%02d.png" % _FIG_N[0])
        fig.savefig(path, dpi=110, bbox_inches="tight")
        print("  [saved] %s" % os.path.relpath(path, ROOT))
    plt.close("all")


sys.path.insert(0, os.path.join(ROOT, "src"))

import community as community_louvain  # noqa: E402,F401  (python-louvain)
import networkx as nx  # noqa: E402,F401
import pandas as pd  # noqa: E402,F401
from networkx.algorithms import community  # noqa: E402,F401

assert os.path.exists(DATASET_PATH), "dataset not found: %s" % DATASET_PATH

# CLAID notebook - Edge betweenness (Girvan–Newman) (30 cells)


# % [cell 06] code
lst_b = nx.algorithms.community.girvan_newman(G)
type(lst_b)

# % [cell 07] code
for x in lst_b:
  print(x)

# % [cell 08] code
colors = ["#00C98D", "#5030C0", "#50F0F0"]
pos = nx.spring_layout(G)
lst_b = community.girvan_newman(G)
color_map_b = {}
keys = G.nodes()
values = "black"
for i in keys:
        color_map_b[i] = values
counter = 0
for x in lst_b:
  print(1)
  for c in x:
    for n in c:
      color_map_b[n] = colors[counter % len(colors)]
    counter = counter + 1
  break
nx.draw_networkx_edges(G, pos)
nx.draw_networkx_nodes(G, pos, node_color=dict(color_map_b).values())
nx.draw_networkx_labels(G, pos)
plt.axis("off")
claid_show()

# % [cell 09] code
modularity = []
for x in lst_b:
  modularity.append(community.modularity(G, x))
modularity

# % [cell 10] code
plt.plot(modularity, 'o')
plt.xlabel('# of clusters')
plt.ylabel('modularity')
claid_show()

# % [cell 11] code
max_modularity = max(modularity)
max_community = None

for comm_set, mod_value in zip(lst_b, modularity):
    if mod_value == max_modularity:
        max_community = comm_set
        break  # Stop after finding the maximum modularity community

if max_community:
    # Community visualization for the max_community
    colors = ["#00C98D", "#5030C0", "#50F0F0", 'red', 'blue']
    pos = nx.spring_layout(G)
    color_map_b = {}
    keys = G.nodes()
    values = "black"
    for i in keys:
        color_map_b[i] = values
    counter = 0
    for x in max_community:
        for n in x:
            color_map_b[n] = colors[counter % len(colors)]
        counter = counter + 1

    nx.draw_networkx_edges(G, pos)
    nx.draw_networkx_nodes(G, pos, node_color=dict(color_map_b).values())
    nx.draw_networkx_labels(G, pos)
    plt.axis("off")
    claid_show()
else:
    print("No community found with maximum modularity.")
