# Part 5: Fast community unfolding (Louvian)
# One section of the CLAID study pipeline - claid_workflow.py runs them all.
"""The CLAID study pipeline, exported from the original Jupyter notebook.

Generated by tools/export_notebook.py - run it from the repository root:

    python exploratory/claid_workflow.py

The runtime fixes it applies are documented in exploratory/README.md. Figures
are written to exploratory/figures/ instead of opening a window.
"""
import os
import sys

import matplotlib

matplotlib.use("Agg")  # headless: every plt.show() is captured by claid_show()
import matplotlib.pyplot as plt  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUTPUT_DIR = os.path.join(HERE, "figures")
DATASET_PATH = os.path.join(ROOT, "data", "Dataset.csv")  # extracted from the dataset zip
RUN_SCRAPER = False  # the example.com word-graph demo needs internet access

os.makedirs(OUTPUT_DIR, exist_ok=True)
_FIG_N = [0]


def claid_show():
    """Save the current figure (the notebook called plt.show() here)."""
    _FIG_N[0] += 1
    fig = plt.gcf()
    if fig.get_axes():
        path = os.path.join(OUTPUT_DIR, "fig_%02d.png" % _FIG_N[0])
        fig.savefig(path, dpi=110, bbox_inches="tight")
        print("  [saved] %s" % os.path.relpath(path, ROOT))
    plt.close("all")


sys.path.insert(0, os.path.join(ROOT, "src"))

import community as community_louvain  # noqa: E402,F401  (python-louvain)
import networkx as nx  # noqa: E402,F401
import pandas as pd  # noqa: E402,F401
from networkx.algorithms import community  # noqa: E402,F401

assert os.path.exists(DATASET_PATH), "dataset not found: %s" % DATASET_PATH

# CLAID study - Fast community unfolding (Louvian) (30 cells)


# % [cell 18] md
# Local moving of nodes: In this phase, each node is moved to the community that results in the highest increase in modularity. The node will remain in the same community if there is no positive gain. This process is applied repeatedly and for all nodes until no further improvement is possible. The first phase of the Louvain algorithm stops when a local maximum of modularity is obtained.
#
#
# Building a new network: In this phase, the algorithm builds a new network considering communities found in the first phase as nodes. The weights of the links between communities are the sum of the weights of the links between their nodes. Once the second phase is completed, the algorithm will reapply the first phase to the resulting network. These steps are repeated until there are no changes in the network and maximum modularity is obtained
#

# % [cell 19] code
# pip install community   (run once: python -m pip install community)

# % [cell 20] code
import networkx as nx
from community import community_louvain
import matplotlib.pyplot as plt

# Assuming G is defined and has nodes and edges added to it
G = nx.Graph()

# Generate a sample graph for demonstration
G.add_edges_from([(1, 2), (2, 3), (3, 4), (4, 1)])

colors = ["#00C98D", "#5030C0", "#50F0F0", 'yellow']
pos = nx.spring_layout(G)
lst_m = community_louvain.best_partition(G)
color_map_b = {}
keys = G.nodes()
values = "black"
for i in keys:
        color_map_b[i] = values

for n in dict(lst_m):
  color_map_b[n] = colors[lst_m[n]]

plt.figure(figsize=(8, 8))  # Increase the figure size
nx.draw_networkx_edges(G, pos)
nx.draw_networkx_nodes(G, pos, node_color=dict(color_map_b).values())
nx.draw_networkx_labels(G, pos)
plt.axis("off")
claid_show()


# % [cell 21] code
import requests
from bs4 import BeautifulSoup
import networkx as nx
import matplotlib.pyplot as plt

# Function to scrape data from a website
def scrape_website(url):
    try:
        response = requests.get(url)
        if response.status_code == 200:
            soup = BeautifulSoup(response.text, 'html.parser')
            # Extract relevant data from the website
            # Example: titles, links, text, etc.
            # For simplicity, let's extract text content
            text_content = soup.get_text()
            return text_content
        else:
            print("Failed to retrieve data from:", url)
            return None
    except Exception as e:
        print("Error occurred:", e)
        return None

# Main function for network analysis
def main():
    # Define the URL to scrape
    url = "https://example.com"

    # Scrape data from the website
    text_content = scrape_website(url)

    # If data is successfully scraped, perform network analysis
    if text_content:
        # Create a graph
        G = nx.Graph()

        # Process text content (you may need more advanced text processing here)
        # For simplicity, let's split text by whitespace
        words = text_content.split()

        # Add nodes and edges to the graph
        for i in range(len(words) - 1):
            word1 = words[i]
            word2 = words[i + 1]
            if not G.has_edge(word1, word2):
                G.add_edge(word1, word2)

        # Visualize the network
        pos = nx.spring_layout(G)
        plt.figure(figsize=(10, 10))
        nx.draw(G, pos, with_labels=True, node_color='skyblue', node_size=1000, edge_color='black', linewidths=1, font_size=15)
        plt.title("Website Network Analysis")
        claid_show()
    else:
        print("Failed to scrape data. Exiting...")

if __name__ == "__main__" and RUN_SCRAPER:
    main()


# % [cell 22] code
# pip install Flask   (run once: python -m pip install Flask)
