# Part 3: Modularity maximization
# One section of the CLAID study pipeline - claid_workflow.py runs them all.
"""The CLAID study pipeline, exported from the original Jupyter notebook.

Generated by tools/export_notebook.py - run it from the repository root:

    python exploratory/claid_workflow.py

The runtime fixes it applies are documented in exploratory/README.md. Figures
are written to exploratory/figures/ instead of opening a window.
"""
import os
import sys

import matplotlib

matplotlib.use("Agg")  # headless: every plt.show() is captured by claid_show()
import matplotlib.pyplot as plt  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUTPUT_DIR = os.path.join(HERE, "figures")
DATASET_PATH = os.path.join(ROOT, "data", "Dataset.csv")  # extracted from the dataset zip
RUN_SCRAPER = False  # the example.com word-graph demo needs internet access

os.makedirs(OUTPUT_DIR, exist_ok=True)
_FIG_N = [0]


def claid_show():
    """Save the current figure (the notebook called plt.show() here)."""
    _FIG_N[0] += 1
    fig = plt.gcf()
    if fig.get_axes():
        path = os.path.join(OUTPUT_DIR, "fig_%02d.png" % _FIG_N[0])
        fig.savefig(path, dpi=110, bbox_inches="tight")
        print("  [saved] %s" % os.path.relpath(path, ROOT))
    plt.close("all")


sys.path.insert(0, os.path.join(ROOT, "src"))

import community as community_louvain  # noqa: E402,F401  (python-louvain)
import networkx as nx  # noqa: E402,F401
import pandas as pd  # noqa: E402,F401
from networkx.algorithms import community  # noqa: E402,F401

assert os.path.exists(DATASET_PATH), "dataset not found: %s" % DATASET_PATH

# CLAID study - Modularity maximization (30 cells)


# % [cell 13] code
community.greedy_modularity_communities(G)

# % [cell 14] code
#Community visualization
colors = ["#00C98D", "#5030C0", "#50F0F0"]
pos = nx.spring_layout(G)
lst_b = community.greedy_modularity_communities(G)
color_map_b = {}
keys = G.nodes()
values = "black"
for i in keys:
        color_map_b[i] = values
counter = 0
for x in lst_b:
  for n in x:
    color_map_b[n] = colors[counter % len(colors)]
  counter = counter + 1

nx.draw_networkx_edges(G, pos)
nx.draw_networkx_nodes(G, pos, node_color=dict(color_map_b).values())
nx.draw_networkx_labels(G, pos)
plt.axis("off")
claid_show()
