# Part 1: intro
# One section of the CLAID study pipeline - claid_workflow.py runs them all.
"""The CLAID study pipeline, exported from the original Jupyter notebook.

Generated by tools/export_notebook.py - run it from the repository root:

    python exploratory/claid_workflow.py

The runtime fixes it applies are documented in exploratory/README.md. Figures
are written to exploratory/figures/ instead of opening a window.
"""
import os
import sys

import matplotlib

matplotlib.use("Agg")  # headless: every plt.show() is captured by claid_show()
import matplotlib.pyplot as plt  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUTPUT_DIR = os.path.join(HERE, "figures")
DATASET_PATH = os.path.join(ROOT, "data", "Dataset.csv")  # extracted from the dataset zip
RUN_SCRAPER = False  # the example.com word-graph demo needs internet access

os.makedirs(OUTPUT_DIR, exist_ok=True)
_FIG_N = [0]


def claid_show():
    """Save the current figure (the notebook called plt.show() here)."""
    _FIG_N[0] += 1
    fig = plt.gcf()
    if fig.get_axes():
        path = os.path.join(OUTPUT_DIR, "fig_%02d.png" % _FIG_N[0])
        fig.savefig(path, dpi=110, bbox_inches="tight")
        print("  [saved] %s" % os.path.relpath(path, ROOT))
    plt.close("all")


sys.path.insert(0, os.path.join(ROOT, "src"))

import community as community_louvain  # noqa: E402,F401  (python-louvain)
import networkx as nx  # noqa: E402,F401
import pandas as pd  # noqa: E402,F401
from networkx.algorithms import community  # noqa: E402,F401

assert os.path.exists(DATASET_PATH), "dataset not found: %s" % DATASET_PATH

# CLAID study - intro (30 cells)


# % [cell 00] code
# pip install igraph   (run once: python -m pip install igraph)
try:
    import igraph as ig  # noqa: F401  (optional: python -m pip install igraph)
except ImportError:  # pragma: no cover - optional dependency
    ig = None

# % [cell 01] code
import pandas as pd
import networkx as nx
from networkx.algorithms import community
import community as community_louvain
import matplotlib.pyplot as plt
try:
    import igraph as ig  # noqa: F401  (optional: python -m pip install igraph)
except ImportError:  # pragma: no cover - optional dependency
    ig = None
# %matplotlib inline  -> handled by the 'Agg' backend in the preamble

# % [cell 02] code
G = nx.karate_club_graph()

# % [cell 03] code
# Define the graph G
G = nx.karate_club_graph()

# Draw the graph
nx.draw_networkx(G)
