#!/usr/bin/env python
"""Convert the CLAID Jupyter notebook into runnable ``.py`` files.

Usage
-----
    python tools/convert_notebook.py
    python tools/convert_notebook.py --notebook <file.ipynb> --outdir notebook_to_py

Outputs (in ``notebook_to_py/``)
-------------------------------
``CLAID_notebook_raw.py``  the notebook verbatim; only ``%magics``, ``!shell``
                          escapes and bare ``pip install`` lines become comments
                          so the file is valid Python.
``CLAID_notebook.py``      the same code with the documented runtime fixes
                          applied (FILE_FIXES below) - this file executes.
``section_N_<slug>.py``    one file per markdown section of the notebook.
``output/``                figures written by ``claid_show()`` at runtime.
``conversion_report.txt``  cell-by-cell map plus the fixes that fired.
"""
from __future__ import annotations

import argparse
import json
import os
import py_compile
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_NB = os.path.join(
    ROOT, "CLAID_Community_Level_Anomaly_and_Influential_user_Detection.ipynb"
)
DEFAULT_OUT = os.path.join(ROOT, "notebook_to_py")

# --------------------------------------------------------------------------- #
# Line-level rewrites that make the notebook valid, non-interactive Python.
# (id, description, compiled regex, replacement)
# --------------------------------------------------------------------------- #
LINE_FIXES = [
    (
        "magic-matplotlib",
        "%matplotlib inline -> 'Agg' backend is chosen by the preamble",
        re.compile(r"^[ \t]*%matplotlib\s+inline[ \t]*$", re.M),
        "# %matplotlib inline  -> handled by the 'Agg' backend in the preamble",
    ),
    (
        "magic-generic",
        "other %magics -> comments",
        re.compile(r"^([ \t]*)%(\w+)(.*)$", re.M),
        r"\1# %\2\3",
    ),
    (
        "shell-pip",
        "!pip install X -> comment + install hint",
        re.compile(r"^([ \t]*)!\s*pip\s+install\s+(.+)$", re.M),
        r"\1# pip install \2   (run once: python -m pip install \2)",
    ),
    (
        "shell-generic",
        "other !shell commands -> comments",
        re.compile(r"^([ \t]*)!\s*(.+)$", re.M),
        r"\1# \2",
    ),
    (
        "bare-pip",
        "bare 'pip install X' (a SyntaxError in Python) -> comment",
        re.compile(r"^([ \t]*)pip\s+install\s+(.+)$", re.M),
        r"\1# pip install \2   (run once: python -m pip install \2)",
    ),
]

# --------------------------------------------------------------------------- #
# Fixes applied only to the executable conversion; all are reported in
# conversion_report.txt so they can be audited against the original notebook.
# (id, description, compiled regex, replacement)
# --------------------------------------------------------------------------- #
FILE_FIXES = [
    (
        "colour-lookup-guard",
        "colors[counter] counted nodes, not colours -> modulo guard",
        re.compile(r"colors\[counter\]"),
        "colors[counter % len(colors)]",
    ),
    (
        "module-shadowing",
        "loop variable 'community' shadowed the networkx community module",
        re.compile(r"for community, mod_value in zip\("),
        "for comm_set, mod_value in zip(",
    ),
    (
        "module-shadowing-2",
        "the same loop assigned max_community = community (shadowed)",
        re.compile(r"max_community = community\b"),
        "max_community = comm_set",
    ),
    (
        "colab-path",
        "hard-coded Colab path /content/Dataset.csv -> repo dataset",
        re.compile(r"dataset_path\s*=\s*[\"']/content/Dataset\.csv[\"']"),
        "dataset_path = str(DATASET_PATH)",
    ),
    (
        "scraper-guard",
        "example.com word-graph demo is off by default (needs internet)",
        re.compile(r'if __name__ == "__main__":'),
        'if __name__ == "__main__" and RUN_SCRAPER:',
    ),
    (
        "show-hook",
        "plt.show() -> claid_show() so figures land in notebook_to_py/output",
        re.compile(r"\bplt\.show\(\)"),
        "claid_show()",
    ),
    (
        "igraph-optional",
        "import igraph made optional (cell 0 only used it to install itself)",
        re.compile(r"^import igraph as ig[ \t]*$", re.M),
        "try:\n"
        "    import igraph as ig  # noqa: F401  (optional: python -m pip install igraph)\n"
        "except ImportError:  # pragma: no cover - optional dependency\n"
        "    ig = None",
    ),
]

RUNNABLE_PREAMBLE = '''"""CLAID notebook converted to a plain Python script.

Generated by tools/convert_notebook.py - run it from the repository root:

    python notebook_to_py/CLAID_notebook.py

The runtime fixes it applies are listed in notebook_to_py/conversion_report.txt.
Figures are written to notebook_to_py/output/ instead of opening a window.
"""
import os
import sys

import matplotlib

matplotlib.use("Agg")  # headless: every plt.show() is captured by claid_show()
import matplotlib.pyplot as plt  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUTPUT_DIR = os.path.join(HERE, "output")
DATASET_PATH = os.path.join(ROOT, "data", "Dataset.csv")  # extracted from the dataset zip
RUN_SCRAPER = False  # the example.com word-graph demo needs internet access

os.makedirs(OUTPUT_DIR, exist_ok=True)
_FIG_N = [0]


def claid_show():
    """Save the current figure (the notebook called plt.show() here)."""
    _FIG_N[0] += 1
    fig = plt.gcf()
    if fig.get_axes():
        path = os.path.join(OUTPUT_DIR, "fig_%02d.png" % _FIG_N[0])
        fig.savefig(path, dpi=110, bbox_inches="tight")
        print("  [saved] %s" % os.path.relpath(path, ROOT))
    plt.close("all")


sys.path.insert(0, os.path.join(ROOT, "src"))

import community as community_louvain  # noqa: E402,F401  (python-louvain)
import networkx as nx  # noqa: E402,F401
import pandas as pd  # noqa: E402,F401
from networkx.algorithms import community  # noqa: E402,F401

assert os.path.exists(DATASET_PATH), "dataset not found: %s" % DATASET_PATH
'''

RAW_PREAMBLE = '''"""CLAID notebook converted verbatim to a plain Python script.

IPython magics (``%...``), shell escapes (``!...``) and bare ``pip install`` lines
are comments so the file parses as Python - nothing else was changed.  Some cells
need optional packages (igraph) or Colab paths, so this file documents the
original work; run CLAID_notebook.py to actually execute the pipeline.
"""
'''

SECTION_PREAMBLE = '# Section %d: %s\n# Part of the CLAID notebook (see CLAID_notebook.py for the full script).\n'


def cell_source(cell):
    src = cell.get("source", "")
    return src if isinstance(src, str) else "".join(src)


def apply_fixes(text, fixes, fired):
    for fid, desc, pattern, repl in fixes:
        text, n = pattern.subn(repl, text)
        if n:
            fired.append((fid, desc, n))
    return text


def slugify(title):
    slug = re.sub(r"[^0-9a-zA-Z]+", "_", title.strip().lower()).strip("_")
    return slug[:48] or "section"


def split_sections(cells):
    """Group cell indices by markdown headings (a section starts at a '# ' cell)."""
    sections = []
    current = (-1, "intro", [])
    for idx, cell in enumerate(cells):
        if cell["cell_type"] == "markdown":
            text = cell_source(cell).strip()
            first = next((ln.strip() for ln in text.split("\n") if ln.strip()), "")
            if first.startswith("#"):
                if current[2]:
                    sections.append(current)
                current = (idx, first.lstrip("# ").strip().replace("**", ""), [])
                continue
        current[2].append(idx)
    if current[2]:
        sections.append(current)
    return sections


def main():
    ap = argparse.ArgumentParser(description="Convert the CLAID notebook to .py files")
    ap.add_argument("--notebook", default=DEFAULT_NB)
    ap.add_argument("--outdir", default=DEFAULT_OUT)
    args = ap.parse_args()

    with open(args.notebook, encoding="utf-8") as fh:
        nb = json.load(fh)
    cells = nb["cells"]
    os.makedirs(os.path.join(args.outdir, "output"), exist_ok=True)

    fired, line_fired = [], []
    raw_cells, run_cells, table = [], [], []
    for idx, cell in enumerate(cells):
        src = cell_source(cell)
        if cell["cell_type"] == "markdown":
            raw_cells.append((idx, "md", src))
            run_cells.append((idx, "md", src))
            continue
        raw = apply_fixes(src, LINE_FIXES, line_fired)
        run = apply_fixes(raw, FILE_FIXES, fired)
        raw_cells.append((idx, "code", raw))
        run_cells.append((idx, "code", run))
        table.append((idx, len(src), len(run)))

    def dump(path, title, preamble, stream):
        out = [preamble, "# %s (%d cells)\n" % (title, len(cells))]
        for idx, kind, text in stream:
            out.append("\n# %% [cell %02d] %s" % (idx, kind))
            if kind == "md":
                for ln in text.split("\n"):
                    out.append("# " + ln if ln.strip() else "#")
            else:
                out.append(text)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write("\n".join(out).rstrip() + "\n")
        return path

    written = [
        dump(
            os.path.join(args.outdir, "CLAID_notebook_raw.py"),
            "CLAID notebook, verbatim conversion",
            RAW_PREAMBLE,
            raw_cells,
        ),
        dump(
            os.path.join(args.outdir, "CLAID_notebook.py"),
            "CLAID notebook, executable conversion",
            RUNNABLE_PREAMBLE,
            run_cells,
        ),
    ]

    sections = split_sections(cells)
    for n, (start, title, idxs) in enumerate(sections, start=1):
        stream = [(i, raw_cells[i][1], run_cells[i][2]) for i in idxs]
        name = "section_%d_%s.py" % (n, slugify(title))
        written.append(
            dump(os.path.join(args.outdir, name), "CLAID notebook - %s" % title,
                 SECTION_PREAMBLE % (n, title) + RUNNABLE_PREAMBLE, stream)
        )

    report = ["CLAID notebook conversion report", "=" * 60,
              "source notebook : %s" % os.path.relpath(args.notebook, ROOT),
              "notebook cells  : %d code / %d markdown" % (
                  sum(1 for c in cells if c["cell_type"] == "code"),
                  sum(1 for c in cells if c["cell_type"] == "markdown")),
              "sections        : %d" % len(sections), "",
              "Line rewrites (both conversions)"]
    for fid, desc, _, _ in LINE_FIXES:
        n = sum(c for f, _, c in line_fired if f == fid)
        report.append("  - %-18s %s  (%d replacement(s))" % (fid, desc, n))
    report += ["", "Runtime fixes (executable conversion only)"]
    for fid, desc, n in fired:
        report.append("  - %-20s %s  (%d replacement(s))" % (fid, desc, n))
    report += ["", "Cell sizes (original -> converted characters)"]
    for idx, a, b in table:
        report.append("  cell %02d: %5d -> %5d" % (idx, a, b))

    checks = []
    for path in written:
        try:
            py_compile.compile(path, doraise=True)
            checks.append("  OK    %s" % os.path.basename(path))
        except py_compile.PyCompileError as exc:
            checks.append("  FAIL  %s: %s" % (os.path.basename(path), exc))
    report += ["", "Syntax check (py_compile)"] + checks
    report += ["", "Generated files"]
    for path in written:
        report.append("  - %s (%d bytes)" % (os.path.relpath(path, ROOT), os.path.getsize(path)))

    with open(os.path.join(args.outdir, "conversion_report.txt"), "w",
              encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(report) + "\n")

    print("\n".join(report))
    return 0 if all(c.startswith("  OK") for c in checks) else 1


if __name__ == "__main__":
    raise SystemExit(main())


